{% set name = "multi_key_dict" %}
{% set version = "2.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: deebdec17aa30a1c432cb3f437e81f8621e1c0542a0c0617a74f71e232e9939e

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - multi_key_dict

about:
  home: https://github.com/formiaczek/multi_key_dict
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Multi key dictionary implementation

extra:
  recipe-maintainers:
    - nicoddemus
